spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mini_project
    username: root
    password: 6720
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

jwt:
  secret:
    key: 037d903153c02c0a50dcb8dc006f749ebcf22be3b441abbea13ec9319845668aab743e36769c40302e33cf931896974d3232b5d44e6f1b0f8f9b9ca20f84d479